name: Autograding Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

       # Set up Java (adjust the version as needed)
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
         java-version: '21'
         distribution: 'temurin'  # You can change this to 'adoptopenjdk' if neede
    - name: Compile Java file
      run: javac main.java || exit 1

      # Run Java program without trace arguments
    - name: Run Java program without trace
      id: run_without_trace
      run: |
        java main > $GITHUB_WORKSPACE/output.txt || exit 1
      continue-on-error: true  # Allow the next steps to run even if this fails

    # Check output when running without trace arguments
    - name: Check output for trace-off
      run: |
        if ! grep -q "n =" $GITHUB_WORKSPACE/output.txt; then
          echo "Error: Trace statements should not be displayed."
          exit 1
        fi
        
    # Run Java program with trace arguments
    - name: Run Java program with trace
      id: run_with_trace
      run: |
         java main trace_on > $GITHUB_WORKSPACE/output.txt || exit 1
      continue-on-error: true  # Allow the next steps to run even if this fails

    # Check output when running with trace arguments
    - name: Check output for trace-on
      run: |
        if ! grep -q "n =" $GITHUB_WORKSPACE/output.txt; then
          echo "Error: Trace statements should be displayed."
          exit 1
        fi






    #  # Compile the Java code
    # - name: Compile Java code
    #   run: |
    #     javac main.java || exit 1 
    #  # Run Java code with trace_on argument (you can modify the arguments as needed)
    # - name: Run Java program with trace_on
    #   run: java main trace_on || exit 1

    #  # Or run Java program without any arguments
    # - name: Run Java program without trace
    #   run: java main || exit 1

    # - name: Compile Java code
    #   run: |
    #     javac main.java || exit 1  # Compile the Main.java file
    #     echo "Compilation complete"
    #     ls -l  # List files to verify if Main.class is generated
    #     if [[ ! -f main.class ]]; then
    #       echo "Error: main.class file not found!";
    #       exit 1;
    #     fi
    # - name: Run program without trace
    #   id: no_trace

    #   run: |
    #     java Main || exit 1  # Run without trace arguments and check output

    # - name: Run program with trace
    #   id: trace_on
    #   run: |
    #     java Main trace_on || exit 1  # Run with trace_on argument and check output

    # - name: Check for trace implementation
    #   run: |
    #     if [[ ! "$(steps.trace_on.outputs.result)" =~ "n = 1" ]]; then
    #       echo "Trace statements are not printed correctly when 'trace_on' is passed.";
    #       exit 1;
    #     fi
    #     echo "Trace statements are printed correctly."


# ////////////////////////////
      
    - name: main_test
      id: main_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: main_test
        setup-command: |
          javac main.java || exit 1 
        command: |
          java main || exit 1
          java main trace_on || exit 1

        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN_TEST_RESULTS: "${{steps.main_test.outputs.result}}"
      with:
        runners: main_test
