name: Autograding Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    #    # Set up Java (adjust the version as needed)
    # - name: Set up Java
    #   uses: actions/setup-java@v3
    #   with:
    #      java-version: '21'
    #      distribution: 'temurin'  # You can change this to 'adoptopenjdk' if neede
    # - name: Compile Java file
    #   run: javac main.java || exit 1
  
    # - name: Check for trace_on condition and if-else structure in code
    #   run: |
    #     if ! grep -q 'args\[0\]\.equals("trace_on")' main.java; then
    #       echo "Error: The condition 'args[0].equals(\"trace_on\")' is missing in main.java."
    #       exit 1
    #     else
    #       echo "Condition 'args[0].equals(\"trace_on\")' found."
    #     fi

    #     if ! grep -q 'if' main.java; then
    #       echo "Error: Both 'if' and 'else' statements are required in main.java."
    #       exit 1
    #     else
    #       echo "'if' and 'else' statements found."
    #     fi
      
    - name: main_test
      id: main_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: main_test
        setup-command: |
          javac main.java || exit 1 
        command: |
          if ! grep -q 'args\[0\]\.equals("trace_on")' main.java; then
          echo "Error: implement the write trace on code...."
          java main
          exit 1
          else
            echo "Correct...."
            java main trace_on
          fi

          if ! grep -q 'if' main.java; then
            echo "Unwanted code modified...."
            exit 1"
          fi
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN_TEST_RESULTS: "${{steps.main_test.outputs.result}}"
      with:
        runners: main_test
