name: Autograding Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Run program without trace
      id: no_trace
      run: |
        java Main || exit 1  # Run without trace arguments and check output

    - name: Run program with trace
      id: trace_on
      run: |
        java Main trace_on || exit 1  # Run with trace_on argument and check output

    - name: Check for trace implementation
      run: |
        if [[ ! "$(steps.trace_on.outputs.result)" =~ "n = 1" ]]; then
          echo "Trace statements are not printed correctly when 'trace_on' is passed.";
          exit 1;
        fi
        echo "Trace statements are printed correctly."



      
    - name: main_test
      id: main_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: main_test
        setup-command: |
          javac main.java || exit 1 
        command: |
          java main
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN_TEST_RESULTS: "${{steps.main_test.outputs.result}}"
      with:
        runners: main_test
