name: Autograding Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'  # Or the version you need
        java-package: jdk
        distribution: 'adoptopenjdk'

    - name: Compile Java code
      run: javac Main.java || exit 1
      
    - name: main_test
      id: main_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: main_test
        setup-command: |
          javac Main.java || exit 1 
        command: ""
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN_TEST_RESULTS: "${{steps.main_test.outputs.result}}"
      with:
        runners: main_test
