name: Autograding Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
         java-version: '21'
         distribution: 'temurin'
    - name: Compile Java file
      run: javac main.java || exit 1
# ///////////
  # Test without trace_on
    - name: Run without trace_on
      run: |
        output=$(java main)
        echo "$output"
        if [[ "$output" != *"Sum = 55"* ]]; then
          echo "Error: Expected 'Sum = 55' without trace_on."
          exit 1
        fi

    # Test with trace_on
    - name: Run with trace_on
      run: |
        output=$(java main trace_on)
        echo "$output"
        if [[ "$output" != *"n = 1"* || "$output" != *"Sum = 55"* ]]; then
          echo "Error: Trace statements missing when trace_on is used."
          exit 1
        fi








      # ?/////////
  
    - name: Compile java 2
      run: |
        if ! grep -q '&& args\[0\]\.equals("trace_on")' main.java; then
          echo "points=5" >> $GITHUB_ENV 
          echo "points=5" >> $GITHUB_OUTPUT
        else
          echo "points=0" >> $GITHUB_ENV 
          echo "points=0" >> $GITHUB_OUTPUT
        fi
    - name: Compile java 3
      run: |
        if ! grep -q 'if' main.java; then
          echo "nwanted code modified...."
          exit 1
        fi
      
    - name: java_code_runner
      id: main_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: main_test
        setup-command: |
          javac main.java || exit 1 
        command: |
          if [ "${{ steps.s_value.outputs.points }}" -eq 5 ]; then
          java main trace_on
          else
            java main
            exit 1
          fi
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN_TEST_RESULTS: "${{steps.main_test.outputs.result}}"
      with:
        runners: main_test
